ads/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import *
app_name = 'ads'

urlpatterns = [
    path('',MainView.as_view(),name='all'),
    path('category/<slug:category_slug>',MainView.as_view(),name='ad_list_by_category'),
    path('mine',UserAdsView.as_view(),name='mine'),
    path('create',AdCreate.as_view(), name='ad_create'),
    # path('ad/<int:pk>/edit',AdUpdate.as_view(), name='ad_update'),
    path('ad/<int:pk>/update',AdUpdate.as_view(), name='ad_update'),
    path('ad/<int:pk>/delete',AdDelete.as_view(), name='ad_delete'),
    path('ad/<int:pk>/detail',AdDetail.as_view(), name='ad_detail'),
    path('ad_picture/<int:pk>', stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
        CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        CommentDeleteView.as_view(success_url=reverse_lazy('ads')), name='ad_comment_delete'),
    path('ad/<int:pk>/favorite',
    AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
        DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

adsite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView
from ads.views import MainView

urlpatterns = [
    path('',MainView.as_view(),name='all'),
    path('admin/', admin.site.urls),
    path('ads/', include('ads.urls',namespace='ads')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('registration/', include('registration.urls',namespace='registration')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/',include('orders.urls', namespace='orders'))
]

# Serve the favicon - Keep for later
# urlpatterns += [
#     path('favicon.ico', serve, {
#             'path': 'favicon.ico',
#             'document_root': os.path.join(BASE_DIR, 'home/static'),
#         }
#     ),
# ]

cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'

urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:ad_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:ad_id>/', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path
from . import views
app_name = 'orders'
urlpatterns = [
    path('create/', views.OrderFormView.as_view(), name='order_create'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

class CartAddAdForm(forms.Form):
    quantity = forms.IntegerField(required=False,initial=1,widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render,redirect,get_object_or_404

from django.views.decorators.http import require_POST
from ads.models import Ad
from .cart import Cart
from .forms import CartAddAdForm


@require_POST
def cart_add(request,ad_id):
    cart = Cart(request)
    ad = get_object_or_404(Ad,id=ad_id)
    form = CartAddAdForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(ad)
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request,ad_id):
    cart = Cart(request)
    ad = get_object_or_404(Ad,id=ad_id)
    cart.sub(ad)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request,'cart/detail.html',{'cart':cart})

cart/templates/cart/detail.html
{% extends "base_bootstrap.html" %}
{% load static %}
{% block content %}
  <div class="">
    <h1>Your shopping cart</h1>
    <div class="row" style="margin-top:2em">
      <div class="col-xs-12 col-md-8">
        <table class="table table-bordered table-hover table-striped">
          <thead class="thead-light">
            <tr>
              <th>Image</th>
              <th>Product</th>
              <th>Price</th>
              <th>Edit</th>
            </tr>
          </thead>
          <tbody style="margin-top:1em">
            {% for item in cart %}
              {% with ad=item.ad%}
                <tr>
                  <td>
                    <a href="{{ ad.get_absolute_url }}">
                      {% if ad.content_type %}
                        <img style="width:4em; height:4em;" class="card-img-top" src="{% url 'ads:ad_picture' ad.id %}">
                      {% else %}
                        <img class="card-img-top" src="https://dummyimage.com/600x700/dee2e6/6c757d.jpg" alt="..." />
                      {% endif %}
                    </a>
                  </td>
                  <td>{{ ad.title }}</td>
                  <td> {{ ad.price }}</td>
                  <td>
                    <form class="" action='{% url "cart:cart_remove" ad.id %}' method="post">
                      {% csrf_token %}
                      <button class="btn btn-danger" type="submit" name="button">
                        <i class="fa fa-trash"></i>
                      </button>
                    </form>
                  </td>
                </tr>
              {% endwith %}
            {% empty %}
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="col-xs-12 col-md-4 bg-light m-0 px-2">
          <h3>Summary</h3>
          <hr>
          <div class="">
            <i class="font-weight-bolder">Have a coupon?</i>
            <form class="" action="#!" method="post">
              <div style="display:flex; flex-direction:row;" class="">
                <input style="width:70%" type="text" class='' name="" placeholder='Enter coupon code...' value="">
                <button style="width:30%" class="btn btn-secondary" type="button" name="button">Apply</button>
              </div>
            </form>
            <hr>
            <div class="card" style='margin:0; padding:0; width:100%;'>
              <div class="card-body">
                <div class="card-text">
                  <dl class="row">
                    <dt class="col-12 col-lg-5">Total Price</dt>
                    <dd class="col-12 col-lg-7 text-right">${{ cart.get_total_price }}</dd>
                  </dl>
                  <dl class="row">
                    <dt class="col-12 col-lg-5">Discount</dt>
                    <dd class="col-12 col-lg-7 text-right">-$0.00 </dd>
                  </dl>
                  <dl class="row">
                    <dt class="col-12 col-lg-5">Total</dt>
                    <dd class="col-12 col-lg-7 text-right">${{ cart.get_total_price }}</dd>
                  </dl>
                </div>
              </div>
              <div class="card-footer text-right">
                <a class="btn btn-success" href='{% url "orders:order_create"%}' >Checkout</a>
                <a class="btn btn-info" href='{% url "ads:all"%}' >Continue Shopping</a>
              </div>
            </div>
          </div>
      </div>

    </div>
  </div>



{% endblock %}