ads/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import *
app_name = 'ads'

urlpatterns = [
    path('',MainView.as_view(),name='all'),
    path('category/<slug:category_slug>',MainView.as_view(),name='ad_list_by_category'),
    path('mine',UserAdsView.as_view(),name='mine'),
    path('create',AdCreate.as_view(), name='ad_create'),
    # path('ad/<int:pk>/edit',AdUpdate.as_view(), name='ad_update'),
    path('ad/<int:pk>/update',AdUpdate.as_view(), name='ad_update'),
    path('ad/<int:pk>/delete',AdDelete.as_view(), name='ad_delete'),
    path('ad/<int:pk>/detail',AdDetail.as_view(), name='ad_detail'),
    path('ad_picture/<int:pk>', stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
        CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        CommentDeleteView.as_view(success_url=reverse_lazy('ads')), name='ad_comment_delete'),
    path('ad/<int:pk>/favorite',
    AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
        DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

adsite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView
from ads.views import MainView

urlpatterns = [
    path('',MainView.as_view(),name='all'),
    path('admin/', admin.site.urls),
    path('ads/', include('ads.urls',namespace='ads')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('registration/', include('registration.urls',namespace='registration')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/',include('orders.urls', namespace='orders'))
]

# Serve the favicon - Keep for later
# urlpatterns += [
#     path('favicon.ico', serve, {
#             'path': 'favicon.ico',
#             'document_root': os.path.join(BASE_DIR, 'home/static'),
#         }
#     ),
# ]

cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'

urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:ad_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:ad_id>/', views.cart_remove, name='cart_remove'),
]

ads/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator
from django.conf import settings
from django.urls import reverse
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200,unique=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('ads:ad_list_by_category', args=[self.slug])

class Ad(models.Model):
    title = models.CharField(
        max_length = 200,
        validators = [MinLengthValidator(2,"Title must be greater than 2 characters")]
    )
    category = models.ForeignKey(Category,related_name='ads', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits= 7, decimal_places=2,null=True)
    text = models.TextField()
    #Picture
    picture = models.BinaryField(null=True,editable=True)
    content_type = models.CharField(max_length=256, null=True, blank=True, help_text='The MIMEType of the file')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete = models.CASCADE)
    favorites = models.ManyToManyField(settings.AUTH_USER_MODEL,
        through='Fav', related_name='favorite_ads')
    comments = models.ManyToManyField(settings.AUTH_USER_MODEL,
        through='Comment', related_name='comments_owned')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('ads:ad_detail', args=[self.id])

class Fav(models.Model) :
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # https://docs.djangoproject.com/en/3.0/ref/models/options/#unique-together
    class Meta:
        unique_together = ('ad', 'user')

    def __str__(self) :
        return '%s likes %s'%(self.user.username, self.ad.title[:10])

class Comment(models.Model) :
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")]
    )
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        if len(self.text) < 15 : return self.text
        return self.text[:11] + ' ...'

ads/forms.py
from django.forms import *
from django import forms
from django.core.files.uploadedfile import InMemoryUploadedFile
from ads.humanize import naturalsize
from .models import *
from django.core.exceptions import ValidationError
from django.core import validators

# strip means to remove whitespace from the beginning and the end before storing the column
class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True,widget=forms.Textarea)
class CreateForm(ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)
    picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    upload_field_name = 'picture'
    class Meta:
        model = Ad
        fields = ['title', 'category','price', 'text', 'picture']  # Picture is manual
    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < "+self.max_upload_limit_text+" bytes")

    # Convert uploaded File object to a picture
    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture   # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()
        return instance

# https://docs.djangoproject.com/en/3.0/topics/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/3.0/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other

ads/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from .forms import *
from .owner import *
from django.views import View
from django.views.generic import CreateView,UpdateView, DeleteView,DetailView,ListView
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError
from cart.forms import CartAddAdForm

from django.db.models import Q

# Create your views here.

class MainView(ListView):
    model = Ad
    category_slug=None
    def get(self,request,category_slug=None):
        self.category_slug = category_slug
        return super().get(self,request,category_slug=None)
    def get_queryset(self):
        qs = super().get_queryset()
        if self.category_slug:
            sel_category = get_object_or_404(Category,slug=self.category_slug)
            qs = qs.filter(category=sel_category)
        return qs
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['search'] = self.request.GET.get('search',False)
        if self.category_slug:
            context['category'] = self.category_slug
        if context['search']:
            search = context['search']
            context['object_list'] = context['ad_list'] = context['object_list'].filter(Q(title__contains=search)|Q(text__contains=search))
        favorites = list()
        if self.request.user.is_authenticated:
            rows = self.request.user.favorite_ads.values('id')
            favorites = [ row['id'] for row in rows ]
        context['favorites'] = favorites
        context['categories'] = Category.objects.all()
        return context

class UserAdsView(LoginRequiredMixin,MainView):
    model = Ad
    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(owner=self.request.user)
        return qs
class AdCreate(LoginRequiredMixin,View):
    template_name = 'ads/ad_create_form.html'
    success_url = reverse_lazy('ads:all')
    def get(self,request):
        form = CreateForm()
        ctx = {
            'form':form
            }
        return render(request,self.template_name,ctx)
    def post(self,request):
        form = CreateForm(request.POST,request.FILES)
        if not form.is_valid():
            ctx = {
            'form':form
            }
            return render(request,self.template_name,ctx)
        f = form.save(commit=False)
        f.owner = request.user
        f.save()
        return redirect(self.success_url)
    pass
class AdDetail(OwnerDetailView):
    model = Ad
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print('logingng: ',self.request.user,self.request.user.is_authenticated)
        x = context['object']
        comments = Comment.objects.filter(ad=x).order_by('-updated_at')

        if self.request.user.is_authenticated:
            comment_form = CommentForm()
            context['comment_form'] = comment_form
            print('checkekekekeek:  ',context['comment_form'])
        # Call the base implementation first to get a context
        # Add in the publisher
        context['comments'] = comments
        context['cart_ad_form'] = CartAddAdForm()
        return context
    # def get(self, request, pk) :
    #     x = Ad.objects.get(id=pk)
    #     comments = Comment.objects.filter(ad=x).order_by('-updated_at')
    #     comment_form = CommentForm()
    #     context = { 'ad' : x, 'comments': comments, 'comment_form': comment_form }
    #     return render(request, self.template_name, context)
    pass

class AdUpdate(LoginRequiredMixin,View):
    template_name = 'ads/ad_update_form.html'
    success_url = reverse_lazy('ads:all')
    def get(self,request,pk):
        ins = get_object_or_404(Ad,id=pk, owner=self.request.user)
        form = CreateForm(instance=ins)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)
    def post(self, request, pk=None):
        ins = get_object_or_404(Ad, id=pk, owner=self.request.user)
        form = CreateForm(request.POST, request.FILES, instance=ins)
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)
        mdl = form.save(commit=True)
        return redirect(self.success_url)
    pass
class AdDelete(OwnerDeleteView):
    model = Ad
    template_name_suffix = '_delete_form'
    success_url = reverse_lazy('ads:all')
    pass

class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        f = get_object_or_404(Ad, id=pk)
        comment = Comment(text=request.POST['comment'], owner=request.user, ad=f)
        comment.save()
        return redirect(reverse('ads:ad_detail', args=[pk]))

class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = "ads/comment_delete.html"

    # https://stackoverflow.com/questions/26290415/deleteview-with-a-dynamic-success-url-dependent-on-id
    def get_success_url(self):
        ad = self.object.ad
        return reverse('ads:ad_detail', args=[ad.id])

@method_decorator(csrf_exempt, name='dispatch')
class AddFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        print("Add PK",pk)
        ad = get_object_or_404(Ad, id=pk)
        fav = Fav(user=request.user, ad=ad)
        try:
            fav.save()  # In case of duplicate key
        except IntegrityError as e:
            pass
        return HttpResponse()

@method_decorator(csrf_exempt, name='dispatch')
class DeleteFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        ad = get_object_or_404(Ad, id=pk)
        try:
            fav = Fav.objects.get(user=request.user, ad=ad).delete()
        except Exception as e:
            pass

        return HttpResponse()
def stream_file(request, pk):
    pic = get_object_or_404(Ad, id=pk)
    response = HttpResponse()
    response['Content-Type'] = pic.content_type
    response['Content-Length'] = len(pic.picture)
    response.write(pic.picture)
    return response

ads/templates/base_bootstrap.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<!-- Edit dj4e-samples/settings.py and add APP_NAME = 'DJ4E Samples' or similar -->
<title>{% block title %}ADS SITE{% endblock %}</title>

<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- <link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous"> -->

<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script> -->

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<!-- <script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script> -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

<link rel="stylesheet" href="{% static 'forms/forms.css'%}">
<meta name="dj4e-version" content="2020-10-01">
<style media="screen">
    .navbar-nav > li{
      padding-left:1em;
      padding-right:1em;
    }
  .table td{
    vertical-align: sub;
  }
</style>
<link rel="stylesheet" href="{% static 'base.css'%}">
{% block head %}{% endblock %}

</head>
<body>
{% load app_tags %}
<nav class="navbar navbar-expand-sm navbar-light bg-info text-light">
    <a class="navbar-brand" href="/ads">AD Site</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'ads:all' %}">All Products</a></li>
            <li><hr class="dropdown-divider" /></li>
            <li><a class="dropdown-item" href="#!">Popular Items</a></li>
            <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
          </ul>
        </li>
        <li  class="nav-item {% if request.get_full_path == ads %}class="active"{% endif %}">
            <a class="nav-link" href="{% url 'ads:ad_create' %}">Create Ad</a>
        </li>
        <li  class="nav-item {% if request.get_full_path == ads %}class="active"{% endif %}" >
            <a class="nav-link" href="{% url 'ads:mine' %}">My Ads</a>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right ml-auto navbar-expand-sm">
          <li class="nav-item">
            <form class="form-inline">
                <a href="{% url 'cart:cart_detail'%}" class="btn btn-outline-dark" type="submit">
                    <i class="bi-cart-fill me-1"></i>
                    Cart
                    <span class="badge bg-dark text-white ms-1 rounded-pill">{{ cart|length}}</span>
                </a>
            </form>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a href="#" data-toggle="dropdown" class="dropdown-toggle nav-link text-light">
                    <img style="width: 25px;" src="{{ user|gravatar:60 }}"/><b class="caret"></b>
                </a>
                <ul class="dropdown-menu text-light">
                    <li><a class="nav-link" href="{% url 'logout' %}?next={% url 'ads:all' %}">LogoutX</a></li>
                </ul>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="text-light" href="{% url 'login' %}?next={% url 'ads:all' %}">Login</a>
            </li>
          {% endif %}
      </ul>
    </div>

</nav>
<div class="container-fluid">


{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</html>