ads/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import *
app_name = 'ads'

urlpatterns = [
    path('',MainView.as_view(),name='all'),
    path('category/<slug:category_slug>',MainView.as_view(),name='ad_list_by_category'),
    path('mine',UserAdsView.as_view(),name='mine'),
    path('create',AdCreate.as_view(), name='ad_create'),
    # path('ad/<int:pk>/edit',AdUpdate.as_view(), name='ad_update'),
    path('ad/<int:pk>/update',AdUpdate.as_view(), name='ad_update'),
    path('ad/<int:pk>/delete',AdDelete.as_view(), name='ad_delete'),
    path('ad/<int:pk>/detail',AdDetail.as_view(), name='ad_detail'),
    path('ad_picture/<int:pk>', stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
        CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        CommentDeleteView.as_view(success_url=reverse_lazy('ads')), name='ad_comment_delete'),
    path('ad/<int:pk>/favorite',
    AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
        DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

adsite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView
from ads.views import MainView

urlpatterns = [
    path('',MainView.as_view(),name='all'),
    path('admin/', admin.site.urls),
    path('ads/', include('ads.urls',namespace='ads')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('registration/', include('registration.urls',namespace='registration')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/',include('orders.urls', namespace='orders'))
]

# Serve the favicon - Keep for later
# urlpatterns += [
#     path('favicon.ico', serve, {
#             'path': 'favicon.ico',
#             'document_root': os.path.join(BASE_DIR, 'home/static'),
#         }
#     ),
# ]

cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'

urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:ad_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:ad_id>/', views.cart_remove, name='cart_remove'),
]

ads/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator
from django.conf import settings
from django.urls import reverse
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200,unique=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('ads:ad_list_by_category', args=[self.slug])

class Ad(models.Model):
    title = models.CharField(
        max_length = 200,
        validators = [MinLengthValidator(2,"Title must be greater than 2 characters")]
    )
    category = models.ForeignKey(Category,related_name='ads', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits= 7, decimal_places=2,null=True)
    text = models.TextField()
    #Picture
    picture = models.BinaryField(null=True,editable=True)
    content_type = models.CharField(max_length=256, null=True, blank=True, help_text='The MIMEType of the file')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete = models.CASCADE)
    favorites = models.ManyToManyField(settings.AUTH_USER_MODEL,
        through='Fav', related_name='favorite_ads')
    comments = models.ManyToManyField(settings.AUTH_USER_MODEL,
        through='Comment', related_name='comments_owned')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('ads:ad_detail', args=[self.id])

class Fav(models.Model) :
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # https://docs.djangoproject.com/en/3.0/ref/models/options/#unique-together
    class Meta:
        unique_together = ('ad', 'user')

    def __str__(self) :
        return '%s likes %s'%(self.user.username, self.ad.title[:10])

class Comment(models.Model) :
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")]
    )
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        if len(self.text) < 15 : return self.text
        return self.text[:11] + ' ...'

ads/forms.py
from django.forms import *
from django import forms
from django.core.files.uploadedfile import InMemoryUploadedFile
from ads.humanize import naturalsize
from .models import *
from django.core.exceptions import ValidationError
from django.core import validators

# strip means to remove whitespace from the beginning and the end before storing the column
class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True,widget=forms.Textarea)
class CreateForm(ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)
    picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    upload_field_name = 'picture'
    class Meta:
        model = Ad
        fields = ['title', 'category','price', 'text', 'picture']  # Picture is manual
    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < "+self.max_upload_limit_text+" bytes")

    # Convert uploaded File object to a picture
    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture   # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()
        return instance

# https://docs.djangoproject.com/en/3.0/topics/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/3.0/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other

ads/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from .forms import *
from .owner import *
from django.views import View
from django.views.generic import CreateView,UpdateView, DeleteView,DetailView,ListView
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError
from cart.forms import CartAddAdForm

from django.db.models import Q

# Create your views here.

class MainView(ListView):
    model = Ad
    category_slug=None
    def get(self,request,category_slug=None):
        self.category_slug = category_slug
        return super().get(self,request,category_slug=None)
    def get_queryset(self):
        qs = super().get_queryset()
        if self.category_slug:
            sel_category = get_object_or_404(Category,slug=self.category_slug)
            qs = qs.filter(category=sel_category)
        return qs
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['search'] = self.request.GET.get('search',False)
        if self.category_slug:
            context['category'] = self.category_slug
        if context['search']:
            search = context['search']
            context['object_list'] = context['ad_list'] = context['object_list'].filter(Q(title__contains=search)|Q(text__contains=search))
        favorites = list()
        if self.request.user.is_authenticated:
            rows = self.request.user.favorite_ads.values('id')
            favorites = [ row['id'] for row in rows ]
        context['favorites'] = favorites
        context['categories'] = Category.objects.all()
        return context

class UserAdsView(LoginRequiredMixin,MainView):
    model = Ad
    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(owner=self.request.user)
        return qs
class AdCreate(LoginRequiredMixin,View):
    template_name = 'ads/ad_create_form.html'
    success_url = reverse_lazy('ads:all')
    def get(self,request):
        form = CreateForm()
        ctx = {
            'form':form
            }
        return render(request,self.template_name,ctx)
    def post(self,request):
        form = CreateForm(request.POST,request.FILES)
        if not form.is_valid():
            ctx = {
            'form':form
            }
            return render(request,self.template_name,ctx)
        f = form.save(commit=False)
        f.owner = request.user
        f.save()
        return redirect(self.success_url)
    pass
class AdDetail(OwnerDetailView):
    model = Ad
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print('logingng: ',self.request.user,self.request.user.is_authenticated)
        x = context['object']
        comments = Comment.objects.filter(ad=x).order_by('-updated_at')

        if self.request.user.is_authenticated:
            comment_form = CommentForm()
            context['comment_form'] = comment_form
            print('checkekekekeek:  ',context['comment_form'])
        # Call the base implementation first to get a context
        # Add in the publisher
        context['comments'] = comments
        context['cart_ad_form'] = CartAddAdForm()
        return context
    # def get(self, request, pk) :
    #     x = Ad.objects.get(id=pk)
    #     comments = Comment.objects.filter(ad=x).order_by('-updated_at')
    #     comment_form = CommentForm()
    #     context = { 'ad' : x, 'comments': comments, 'comment_form': comment_form }
    #     return render(request, self.template_name, context)
    pass

class AdUpdate(LoginRequiredMixin,View):
    template_name = 'ads/ad_update_form.html'
    success_url = reverse_lazy('ads:all')
    def get(self,request,pk):
        ins = get_object_or_404(Ad,id=pk, owner=self.request.user)
        form = CreateForm(instance=ins)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)
    def post(self, request, pk=None):
        ins = get_object_or_404(Ad, id=pk, owner=self.request.user)
        form = CreateForm(request.POST, request.FILES, instance=ins)
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)
        mdl = form.save(commit=True)
        return redirect(self.success_url)
    pass
class AdDelete(OwnerDeleteView):
    model = Ad
    template_name_suffix = '_delete_form'
    success_url = reverse_lazy('ads:all')
    pass

class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        f = get_object_or_404(Ad, id=pk)
        comment = Comment(text=request.POST['comment'], owner=request.user, ad=f)
        comment.save()
        return redirect(reverse('ads:ad_detail', args=[pk]))

class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = "ads/comment_delete.html"

    # https://stackoverflow.com/questions/26290415/deleteview-with-a-dynamic-success-url-dependent-on-id
    def get_success_url(self):
        ad = self.object.ad
        return reverse('ads:ad_detail', args=[ad.id])

@method_decorator(csrf_exempt, name='dispatch')
class AddFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        print("Add PK",pk)
        ad = get_object_or_404(Ad, id=pk)
        fav = Fav(user=request.user, ad=ad)
        try:
            fav.save()  # In case of duplicate key
        except IntegrityError as e:
            pass
        return HttpResponse()

@method_decorator(csrf_exempt, name='dispatch')
class DeleteFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        ad = get_object_or_404(Ad, id=pk)
        try:
            fav = Fav.objects.get(user=request.user, ad=ad).delete()
        except Exception as e:
            pass

        return HttpResponse()
def stream_file(request, pk):
    pic = get_object_or_404(Ad, id=pk)
    response = HttpResponse()
    response['Content-Type'] = pic.content_type
    response['Content-Length'] = len(pic.picture)
    response.write(pic.picture)
    return response

ads/templates/ads/ad_create_form.html
{% extends "base_bootstrap.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
  <div class="container mt-5 pt-2">
      <h1>Create A Your New AD</h1>
      <form action="" method="post" id="upload_form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="form-action">
          <div class="row">
            <input class="btn btn-dark border  px-5 border-light mx-1" type="submit" value="Submit">
            <input class="btn btn-secondary px-5 mx-1" type="submit" value="Cancel" onclick="window.location.href='{% url 'ads:all' %}';return false;">
          </div>
        </div>
      </form>
    </div>

<!-- https://stackoverflow.com/questions/2472422/django-file-upload-size-limit -->
<script>
$("#upload_form").submit(function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});
</script>

{% endblock %}

ads/templates/ads/ad_delete_form.html
{% extends "base_bootstrap.html" %}
{% block content %}
    <h1>Ad Delete</h1>
{% load crispy_forms_tags %}
    <form class="" action="{% url 'ads:ad_delete' object.pk%}" method="post">
      {% csrf_token %}
      {{  form|crispy }}
      <p>Are you sure you want to delete ad: {{ object.title }}?</p>
      <input type="submit" name="" value="Yes, delete.">
      <input type="submit" onclick="window.location='{%url 'ads:all' %}'; return false;" name="Cancel" value="Cancel">
    </form>
{% endblock %}

ads/templates/ads/ad_detail.html
{% extends "base_bootstrap.html" %}
{% load humanize %}
{% block head %}
<style>
.overlay{
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 10;
  display: none;
  background-color: rgba(0,0,0,0.5); /*dim the background*/
}
</style>
{% endblock %}

{% block content %}
    <h1>Ads Detail</h1>
    <section class="py-1">
      <div class="container px-4 px-lg-5 my-5">
          <div class="row gx-4 gx-lg-5 align-items-center">
              <div class="col-md-6" >
                {% if object.content_type %}
                  <img class="card-img-top mb-5 mb-md-0" src="{% url 'ads:ad_picture' object.id %}">
                {% else %}
                  <img class="card-img-top mb-5 mb-md-0" src="https://dummyimage.com/600x700/dee2e6/6c757d.jpg" alt="..." />
                {% endif %}
              </div>
              <div style="background-color:rgba(37,162,183, 0.1)" class="col-md-6 py-5">
                  <div class="small mb-1 ">
                    ({{ ad.updated_at|naturaltime }})
                    {% if ad.owner == user %}
                        <a href="{% url 'ads:ad_update' object.id %}"><i class="fa fa-pencil"></i></a> |
                        <a href="{% url 'ads:ad_delete' object.id %}"><i class="fa fa-trash"></i></a>
                    {%endif%}
                  </div>
                  <h1 class="display-5 fw-bolder text-info">{{ object.title }}</h1>
                    <a class="text-primary font-weight-bold"href="{{ object.category.get_absolute_url }}">
                      {{object.category.name}}
                    </a>
                  <div class="fs-5 mb-5">
                      <span>${{ object.price }}</span>
                  </div>
                  <p class="lead">{{object.text}}</p>
                  <div class="d-flex">
                    <form class="form-group" action='{% url "cart:cart_add" object.id %}' method="post">
                      {{ cart_ad_form }}
                      {% csrf_token %}
                      <button class="btn btn-outline-info flex-shrink-0" type="submit">
                          <i class="bi-cart-fill me-1"></i>
                          Add to cart
                      </button>
                    </form>
                  </div>
              </div>
          </div>
      </div>
    </section>
      {% if user.is_authenticated %}
      <br clear="all"/>
        <div class="container">
            {% load crispy_forms_tags %}
            <form method="post" action="{% url 'ads:ad_comment_create' ad.id %}">
                {% csrf_token %}
                <!-- -->
                {{ comment_form|crispy }}
                <!-- -->
                <input class="btn btn-primary" type="submit" value="Submit" />
            </form>
        </div>
        <hr>
      {% endif %}
      {% for comment in comments %}
      <div class="media">
        <button style='width:3rem; height:3rem; border-radius:50%' class="mr-3" src="..." alt="Generic placeholder image">
          <i class="fa fa-solid fa-user-astronaut"></i>
        </button>
        <div class="media-body">
          <h5 class="mt-0">{{ comment.owner }}</h5>
          ({{ comment.updated_at|naturaltime }})<br><br>

          {{ comment.text }}
          {% if user == comment.owner %}
              <a href="{% url 'ads:ad_comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
          {% endif %}
        </div>
      </div>
      <hr>
      {% endfor %}
    <div>
      <a href="{% url 'ads:all' %}" >
          View ads
      </a>|
      {% if user.is_authenticated %}
          <a href="{% url 'logout' %}?next={% url 'ads:all' %}">
              Logout
          </a>
      {% else %}
          <a href="{% url 'login' %}?next={% url 'ads:ad_create' %}">
              Login
          </a>
      {%endif%}
    </div>

{% endblock %}

ads/templates/ads/ad_list.html
{% extends "base_bootstrap.html" %}
{% block head %}{% endblock %}
{% block content %}
    <div class="bg-light py-3">
      <h1 class="">Ads List</h1>
      <div class="col-12 bg-light">
          <form>
            <div style="text-align:right; " class="">
              <div style="display:block; margin:auto; width:100%;" class="form-group">
                <input style="width:50%; display:inline"class="form-control" type="text" placeholder="Search.." name="search"
                {% if search %} value="{{ search }}" {% endif %}
                >
                <button class="btn btn-info btn-sm"type="submit"><i class="fa fa-search"></i></button>
                <a href="{% url 'ads:all' %}"><i class="fa fa-undo"></i></a>
              </div>
            </div>
          </form>
      </div>
    </div>

    <div class="container mt-3">
      <div class="d-flex flex-column">
        <div class="row">
          <div class="col-xs-12 col-md-3 bg-light py-3">
            <div class="">
              <h3>Categories</h3>
              <button style="position:absolute; top:0; right:0;" class="btn btn-light text-info d-md-none d-xs-block" type="button" name="button"  data-toggle="collapse" data-target="#collapseCategory" aria-expanded="false" aria-controls="collapseCategory">
                <i class='fa fa-bars'></i>
              </button>
            </div>
            <div class="show" id='collapseCategory'>
              <ul class="list-group d-sm-inline" >
                <li class="list-group-item {% if not category %}bg-info{% endif %}">
                  <a class="{% if not category %}text-dark font-weight-bold {% else %} text-secondary {% endif %}" href="{% url 'ads:all' %}">All</a>
                </li>
                {% for cat in categories %}
                  <li class="list-group-item {% if category == cat.slug %}bg-info{% endif %}">
                    <a class="{% if category == cat.slug %}text-dark font-weight-bold {% else %} text-secondary {% endif %}" href="{{ cat.get_absolute_url }}">
                      {{cat.name}}
                    </a>
                  </li>
                {% endfor %}

              </ul>
            </div>

          </div>

          <div class="col-xs-12 col-md-9">
            <hr class="col-xs-12 d-xs-block d-md-none mb-4" />
            <div class="col-12 row">
              {% for ad in object_list %}
                <div class="col-xs-12 col-md-6 col-xlg-4">
                  <div class="mb-5">
                    <div  style='text-decoration:none' class="card text-dark h-100">
                      <img src="{% url 'ads:ad_picture' ad.id %}" class="card-img-top" alt="...">
                      <!-- <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." /> -->
                      <div class="card-body  p-4 bg-light">
                        <h5 class="card-title">
                          {{ad.title}}
                        </h5>
                        <div class="card-text">
                          <div class="text-center">
                          ${{ad.price}}
                          </div>
                        </div>
                      </div>
                      <div class="card-footer p-4 pt-0 border-top-0 bg-light">
                        <div class="text-center">
                          <a class="btn btn-outline-dark mt-auto" href="{% url 'ads:ad_detail' ad.id %}">View options</a>
                        </div>
                        {% if ad.owner == user %}
                        <a href="{% url 'ads:ad_update' ad.id %}">Edit</a> |
                        <a href="{% url 'ads:ad_delete' ad.id %}">Delete</a>
                        {%endif%}
                      </div>
                      {% if user.is_authenticated %}
                        <div class="" style="position:absolute; right:0; top:0">
                          <a href="#" onclick=
                              "favPost('{% url 'ads:ad_unfavorite' ad.id %}', {{ ad.id }} );return false;"
                              {% if ad.id not in favorites %} style="display: none;" {% endif %}
                              id="favorite_star_{{ad.id}}">
                          <span class="fa-stack" style="vertical-align: middle;">
                          <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
                          <i class="fa fa-star-o fa-stack-1x"></i>
                          </span>
                          </a>
                          <!-- the second href -->
                          <a href="#" onclick=
                               "favPost('{% url 'ads:ad_favorite' ad.id %}', {{ ad.id }} );return false;"
                              {% if ad.id in favorites %} style="display: none;" {% endif %}
                              id="unfavorite_star_{{ad.id}}">
                          <span class="fa-stack" style="vertical-align: middle;">
                          <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
                          <i class="fa fa-star-o fa-stack-1x"></i>
                          </span>
                          </a>
                        </div>
                      {%endif%}

                    </div>
                  </div>
                </div>
              {% empty %}
                  <div class="card">There are no ads in the database.</div>
              {% endfor %}
            </div>
            <div class="col-12">
              <p>
                  <a href="{% url 'ads:ad_create' %}" >
                      Add an Ad
                  </a>|
                  {% if user.is_authenticated %}
                      <a href="{% url 'logout' %}?next={% url 'ads:all' %}">
                          Logout
                      </a>
                  {% else %}
                      <a href="{% url 'login' %}?next={% url 'ads:all' %}">
                          Login
                      </a>
                  {%endif%}
              </p>
            </div>
          </div>
        </div>

      </div>
    </div>

    <script>
        function favPost(_url,_id){
            let xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function(){
                if (this.readyState == 4 && this.status == 200) {
                 console.log(this.responseText);
                    if (document.getElementById("unfavorite_star_"+_id).style.display=='none'){
                        document.getElementById("unfavorite_star_"+_id).style.display ='inline-block';
                    }else{
                        document.getElementById("unfavorite_star_"+_id).style.display ='none';
                    }

                    if (document.getElementById("favorite_star_"+_id).style.display=='none'){
                        document.getElementById("favorite_star_"+_id).style.display ='inline-block';
                    }else{
                        document.getElementById("favorite_star_"+_id).style.display ='none';
                    }
                    // document.getElementById("unfavorite_star_"+_id).toggle();
                    // document.getElementById("favorite_star_"+_id).toggle();
                }
            }
            xhttp.open("POST", _url, true);
            xhttp.send();
        }
    </script>

{% endblock %}

ads/templates/ads/ad_update_form.html
{% extends "base_bootstrap.html" %}
{% block content %}
    <div class="container my-2">
      <h1>Update Your AD</h1>
      {% load crispy_forms_tags %}
      <form class="" method="post" enctype="multipart/form-data" >
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" name="Submit" value="Submit">
        <input type="submit" onclick="window.location='{%url 'ads:all' %}'; return false;" name="Cancel" value="Cancel">
      </form>
    </div>
{% endblock %}

ads/templates/ads/comment_delete.html
{% extends "base_bootstrap.html" %}
{% block content %}
    <h1>Comment Delete</h1>
{% load crispy_forms_tags %}
    <form class="" method="post">
      {% csrf_token %}
      {{  form|crispy }}
      <p>Are you sure you want to delete comment: {{ object.text }}?</p>
      <input type="submit" name="" value="Yes, delete.">
      <input type="submit" onclick="window.location='{%url 'ads:all' %}'; return false;" name="Cancel" value="Cancel">
    </form>
{% endblock %}